#----------------Common Properties across all profiles---------
server:
  port: 8181
  servlet:
    context-path: "/"
    
logging:
  level:
    .: error
    org.springframework: ERROR
    com.amsidh.mvc: INFO
# Logs the JDBC parameters passed to a query
    org.hibernate:
      SQL: debug
      type: trace
      additivity: false    

#mongo database config
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/jwt_db?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
     
    
      
 # App Properties     
app:
  jwtSecret: amsidhSecretKey
  jwtExpirationMs: 86400000      